### ISSUE TITLE
unable to use pluggin 

### ISSUE THREAD

**Issue by technodict** [art1fa/minimalX#10]
For some reason i am not able to use this plug-in.
On running pelican i get the following error CRITICAL: ValueError: substring not found.

I tried un-installing/ installing the plugin using pelican-theme -r without success

**Comment by art1fa** [comment]
I am currently not using `pelican-themes`, so I can't comment on that, sorry...
However, using the theme as suggested in the Wiki by setting a variable `THEME` in your `pelicanconf.py` works totally fine for me.

**Comment by technodict** [comment]
getting the same issue after installing it the way the Wiki suggested

(user) user@user:~/Downloads/websitestuff/PELICAN/mysite$ make html
pelican /home/user/Downloads/websitestuff/PELICAN/mysite/content -o /home/user/Downloads/websitestuff/PELICAN/mysite/output -s /home/user/Downloads/websitestuff/PELICAN/mysite/pelicanconf.py 
CRITICAL: ValueError: substring not found
Makefile:65: recipe for target 'html' failed
make: *** [html] Error 1

Any suggestions to resolve this ?

**Comment by romainx** [comment]
This is due to this line in `base.html`.

```
{{ AUTHOR[0] + AUTHOR[AUTHOR.index(" ")+1] }}
```
If the `AUTHOR` variable in your `pelicanconf.py` does not contain a space it will fail.

**Comment by technodict** [comment]
Here is the block of code from ~/minmalX/templates/base.html

    
55        <a href="{{ SITEURL }}" id=logo title="Home">{{ AUTHOR[0] + AUTHOR[AUTHOR.index(" ")+1] }}</a>         

How to you say the spaces should be ?
currently in pelicanconfig.py 

AUTHOR(space)=(space)"USER"

**Comment by romainx** [comment]
No the theme expects that you have a space in the author name for example:
```
AUTHOR = John Doe
```
Because the theme tries to extract the initials based on the space in the author name.
