### ISSUE TITLE
CRITICAL: UndefinedError: 'tag_cloud' is undefined

### ISSUE THREAD

**Issue by junyanwu** [art1fa/minimalX#11]
After I added `THEME = "/home/sigma/Documents/myblog/themes/minimalX"` in `pelicanconf,py` and excuted `pelican content`, I got an error `CRITICAL: UndefinedError: 'tag_cloud' is undefined` 

What should i do?

**Comment by art1fa** [comment]
If you like to include the tag cloud, then you need to include the respective pelican plugin as described in the [Wiki](https://github.com/art1fa/minimalX/wiki#tag-cloud).

**Comment by junyanwu** [comment]
thks
