### ISSUE TITLE
SHARE_BUTTONS

### ISSUE THREAD

**Issue by DorKeinath** [art1fa/minimalX#7]
After installation on `make devserver` or `pelican` (like described in your wiki) I've got 
> jinja2.exceptions.UndefinedError: 'SHARE_BUTTONS' is undefined

while parsing File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 430
in getattr
   return getattr(obj, attribute)

Where and how do I define this button or how can I deactivate it?

**Comment by art1fa** [comment]
The theme now doesn't require a SHARE_BUTTONS variable to be set in your `pelicanconf.py` anymore. So if you don't need any share buttons, the section would not appear and your project compiles successfully.

**Comment by DorKeinath** [comment]
Great! Thank you!
