### ISSUE TITLE
Hint for tag_cloud

### ISSUE THREAD

**Issue by DorKeinath** [art1fa/minimalX#8]
In README.md you mention that you use a tag-cloud-plugin. May be it would be a good idea to provide a [link](https://github.com/art1fa/art1fa.github.io-src/tree/0dbd122664229c3c9b2ca3df2c0be2d9798eff41/plugins) to the used plugin. Otherwise if not installed you get the error `CRITICAL: UndefinedError: 'tag_cloud' is undefined`.

**Comment by art1fa** [comment]
It's in the [Wiki](https://github.com/art1fa/minimalX/wiki) :)
