### ISSUE TITLE
Manual social media icons

### ISSUE THREAD

**Issue by DorKeinath** [art1fa/minimalX#9]
I would like to integrate a link to an article with an icon from fontawesome.

With
`SOCIAL = (('commenting-o', '/pages/kontakt.html'),
        ('rss', 'feed.html'),
        ('github', 'https://github.com/DorKeinath')
         )`
in pelicanconf.py I get the right behavior on top:

![auswahl_302](https://user-images.githubusercontent.com/16624390/31852567-1b0a1ae2-b67a-11e7-82ef-16c22a9b689c.png)

But in the footer it's wrong:

![auswahl_303](https://user-images.githubusercontent.com/16624390/31852570-265ee4ae-b67a-11e7-80fb-ed908e4553f7.png)
It should be **Kontakt**, **RSS**, **GitHub**.

I tried with expanding SOCIAL to 3 arguments for example 
`SOCIAL = (('GitHub', 'https://github.com/...' , 'github')...`
 and changed 
`{% for name, link in SOCIAL %}` in base.html to `{% for name, link, icon in SOCIAL %}` 

but it doesn't work. Can you give me a hint?

**Comment by art1fa** [comment]
Mh I originally design the Social Media section in the footer to link to your actual social media pages, meaning Facebook, Instagram, Twitter etc. 
I know that the current solution is quite simple, but good enough for me right know.
